# Generated by Django 6.0 on 2025-12-21 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='event',
        ),
    ]
