# Generated by Django 6.0 on 2025-12-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveler',
            name='nationality',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
