# Generated by Django 6.0 on 2025-12-24 19:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='agency.tour')),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.traveler')),
            ],
        ),
        migrations.CreateModel(
            name='TravelerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy', models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this the current location')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.tour')),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='accounts.traveler')),
            ],
        ),
        migrations.CreateModel(
            name='TravelerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('paid', 'Paid'), ('failed', 'Failed')], default='initiated', max_length=20)),
                ('amount', models.IntegerField(help_text='Amount in halalas')),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('moyasar_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('transaction_url', models.URLField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.tour')),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.traveler')),
            ],
        ),
    ]
