# Generated by Django 6.0 on 2025-12-24 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_merge_0002_agencysubscription_0002_tour_agency'),
        ('traveler', '0002_alter_travelerpayment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='agency.tour'),
        ),
    ]
