# Generated by Django 5.2.7 on 2025-12-21 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriptionType', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tours_limit', models.IntegerField(blank=True, null=True)),
                ('supervisors_limit', models.IntegerField(blank=True, null=True)),
                ('travelers_limit', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.agency')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agency.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('travelers', models.PositiveIntegerField(help_text='Max capacity (number of travelers)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days', models.PositiveIntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tour_images/')),
                ('tour_guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.tourguide')),
            ],
        ),
        migrations.CreateModel(
            name='TourSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('activity_title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location_name', models.CharField(max_length=255)),
                ('location_url', models.URLField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='agency.tour')),
            ],
        ),
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius_meters', models.PositiveIntegerField(help_text='Allowed distance from activity location in meters')),
                ('is_active', models.BooleanField(default=True)),
                ('trigger_on_enter', models.BooleanField(default=False)),
                ('trigger_on_exit', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geofence', to='agency.tourschedule')),
            ],
        ),
        migrations.CreateModel(
            name='GeofenceEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('enter', 'Enter'), ('exit', 'Exit')], max_length=10)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('geofence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='agency.geofence')),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_events', to='accounts.traveler')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'unique_together': {('traveler', 'geofence', 'event_type')},
            },
        ),
    ]
