# Generated by Django 6.0 on 2025-12-23 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='accounts.agency'),
        ),
    ]
