# Generated by Django 6.0 on 2025-12-23 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_agencysubscription'),
        ('agency', '0002_tour_agency'),
    ]

    operations = [
    ]
