# Generated by Django 6.0 on 2025-12-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_remove_tour_supervisor_tourschedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourschedule',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='tourschedule',
            name='longitude',
        ),
        migrations.AddField(
            model_name='tourschedule',
            name='location_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
