# Generated by Django 6.0 on 2025-12-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_remove_tourschedule_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='days',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
