# Generated by Django 6.0 on 2025-12-20 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('agency', '0008_tour_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourschedule',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='tourschedule',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radius_meters', models.PositiveIntegerField(help_text='Allowed distance from activity location in meters')),
                ('is_active', models.BooleanField(default=True)),
                ('trigger_on_enter', models.BooleanField(default=False)),
                ('trigger_on_exit', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geofence', to='agency.tourschedule')),
            ],
        ),
        migrations.CreateModel(
            name='GeofenceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('enter', 'Enter'), ('exit', 'Exit')], max_length=10)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('geofence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='agency.geofence')),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_events', to='accounts.traveler')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'unique_together': {('traveler', 'geofence', 'event_type')},
            },
        ),
    ]
