# Generated by Django 6.0 on 2025-12-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backOffice', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelagency',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='travelagency',
            name='rejectionReason',
            field=models.TextField(blank=True),
        ),
    ]
